server {
    server_tokens off;
    client_max_body_size 100m;

    listen 443 ssl;
    listen [::]:443 ssl;

    ssl_certificate /var/certs/blog.loc+1.pem;
    ssl_certificate_key /var/certs/blog.loc+1-key.pem;

    server_name blog.loc *.blog.loc;
    error_log  /var/log/nginx/blog_loc.error.log;
    access_log /var/log/nginx/blog_loc.access.log;
    root /var/www/html/public;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    index index.php index.html;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass blog_php_8.2:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}

server {
    server_tokens off;

    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _ blog.loc *.blog.loc localhost;
    root /var/www/html/public;

    index index.php index.html;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass blog_php_8.2:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
